### ISSUE TITLE
"Ports Are Not Available" From Docker Container (MacOS)

### ISSUE THREAD

**Issue by AidanGood** [Josh-XT/Agent-LLM#61] opened 2023-04-24 04:19 UTC
When trying to run the docker container, I'd get:

`Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use` 

After looking around for what was using this port, I discovered that since [MacOS 12 port 5000 (and 7000) is used for AirPlay](https://apple.stackexchange.com/questions/431154/controlcenter-app-listens-to-port-5000-tcp-on-monterey-os-is-that-normal-why-d). Simple solution is to turn off AirPlay Reciever in the settings, or change the port used by the container, but figured I'd post this here for anyone else who is using a mac and running into the same issue. Might also want to mention this somewhere in the readme?

**Comment by Josh-XT** [comment] 2023-04-24 04:26
> When trying to run the docker container, I'd get:
> 
> `Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:5000 -> 0.0.0.0:0: listen tcp 0.0.0.0:5000: bind: address already in use`
> 
> After looking around for what was using this port, I discovered that since [MacOS 12 port 5000 (and 7000) is used for AirPlay](https://apple.stackexchange.com/questions/431154/controlcenter-app-listens-to-port-5000-tcp-on-monterey-os-is-that-normal-why-d). Simple solution is to turn off AirPlay Reciever in the settings, or change the port used by the container, but figured I'd post this here for anyone else who is using a mac and running into the same issue. Might also want to mention this somewhere in the readme?

Big oof apple lol. That is the default Flask port also. We're using FastAPI currently. I believe you can change the port in the docker compose file but I haven't personally tried running the back end on a different port.

**Comment by bigr00** [comment] 2023-04-24 04:59
I tried changing the port and unfortunately it breaks the frontend, have not found why yet.

**Comment by bigr00** [comment] 2023-04-24 05:14
I changed the port mapping in the Docker compose file:
![Screenshot 2023-04-24 at 08 12 13](https://user-images.githubusercontent.com/28863322/233905374-ef238430-ea72-46d5-a88a-d0894b6b02be.png)

The docker container runs, FastAPI is up and running, but frontend does not connect to it:
![Screenshot 2023-04-24 at 08 13 29](https://user-images.githubusercontent.com/28863322/233905532-1435194e-d911-4cbf-b1f3-947ebb284a62.png)

**Comment by bigr00** [comment] 2023-04-24 05:18
It's fair to say now that it does not work on MacOS currently.

**Comment by bigr00** [comment] 2023-04-24 05:57
The problem is with all the hardcoded URL-s in the frontend. Had to replace 31 port definitions, rebuild the Docker image with no cache enabled (uvicorn caches the initial port) and then finally got the website to work.

It took about an hour of modifications, will fork and post it here.

**Comment by Captain-Bacon** [comment] 2023-04-24 09:33
If you turn off all the airplay you can get it to run, but then i find that i have 'network error' constantly.  Same error as in the closed issue ticket.  I am also running on a macbook, same as the other issues author.

**Comment by Captain-Bacon** [comment] 2023-04-24 11:27
> The problem is with all the hardcoded URL-s in the frontend. Had to replace 31 port definitions, rebuild the Docker image with no cache enabled (uvicorn caches the initial port) and then finally got the website to work.

any chance of a walkthough on this?  I have 34 instances of '5000' showing up, and as you only mention 31, I assume that some of them should not be touched?

**Comment by Josh-XT** [comment] 2023-04-24 12:40
> @bigr00 can you make a PR with just the changes you made?

Just pushed out a docker-compose-mac.yml matching @bigr00's example above.

Mac Users: 
```
docker-compose -f docker-compose-mac.yml up -d --build
```

Please give it a try and let me know how it goes.

**Comment by Josh-XT** [comment] 2023-04-24 13:21
https://github.com/nomic-ai/pygpt4all/issues/57

It might be worth seeing the latest comment on that one, might help with getting pyllamacpp working.

**Comment by Josh-XT** [comment] 2023-04-24 13:29
> 

Correct, you can probably use the normal docker-compose in that case.

**Comment by Captain-Bacon** [comment] 2023-04-24 13:37
@Josh-XT  I maybe being utterly ignorant, but I'm not sure how that helps?  Sorry!

running the normal docker - compose gives me a network error, and the docker for mac won't work as it's arm based, and i'm on the intel?

**Comment by Josh-XT** [comment] 2023-04-24 13:55
> 

The mac one would still work for you, it isn't arm based, it just makes your computer build the docker image instead of pulling it from GitHub.  

You may need to try this since you've already tried running it before:

```
docker-compose down
docker-compose -f docker-compose-mac.yml down
```

Then do:

```
docker-compose -f docker-compose-mac.yml up --build -d
```

**Comment by Aopenz** [comment] 2023-04-24 14:05
=> ERROR [base  7/12] RUN pip install --no-cache-dir -r requirements-mac  1.7s
------                                                                          
 > [base  7/12] RUN pip install --no-cache-dir -r requirements-mac.txt:         
#0 0.269 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-mac.txt'
------
failed to solve: executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements-mac.txt]: exit code: 1

**Comment by Josh-XT** [comment] 2023-04-24 14:09
> ## => ERROR [base 7/12] RUN pip install --no-cache-dir -r requirements-mac 1.7s
> > [base  7/12] RUN pip install --no-cache-dir -r requirements-mac.txt:
> > #0 0.269 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-mac.txt'
> 
> failed to solve: executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements-mac.txt]: exit code: 1

You'll need to pull the latest to get the file.

**Comment by avatarneil** [comment] 2023-04-24 14:12
I believe that the `Dockerfile-mac-backend` file is missing a `COPY requirements-mac.txt ./` statement. If you add that right after the line that copies `requirements.txt`, it ought to work.

**Comment by Captain-Bacon** [comment] 2023-04-24 14:16
the mac version needs the following bold added:

# Install FastAPI app dependencies
FROM python:3.10-slim-buster AS base
WORKDIR /app
COPY requirements**-mac**.txt ./
RUN apt-get update
RUN apt-get install -y --no-install-recommends git build-essential
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get remove -y git build-essential
RUN apt-get install libgomp1 -y
RUN apt-get install git -y
RUN apt-get autoremove -y
RUN rm -rf /var/lib/apt/lists/*

# Run FastAPI app with Uvicorn
FROM base AS uvicorn
COPY . /app
EXPOSE 5000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]

then all is golden

**Comment by Captain-Bacon** [comment] 2023-04-24 14:17
maybe i spoke too soon:


failed to solve: executor failed running [/bin/sh -c apt-get install -y --no-install-recommends git build-essential]: exit code: 100

**Comment by Josh-XT** [comment] 2023-04-24 14:18
Just pushed out an update to fix the dockerfile

**Comment by Josh-XT** [comment] 2023-04-24 14:24
Thanks for the patience and testing everyone!  Let me know if this is resolved for anyone after that last update.

**Comment by Aopenz** [comment] 2023-04-24 15:11
Unable to install requirements-mac.txt, always stuck at step 7：
=> ERROR [base  7/12] RUN pip install --no-cache-dir -r requirements-m  153.1s
------                                                                          
 > [base  7/12] RUN pip install --no-cache-dir -r requirements-mac.txt:         
#0 0.424 Collecting git+https://github.com/huggingface/transformers (from -r requirements-mac.txt (line 9))                                                     
#0 0.424   Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-_esqfh3v                                                                   
#0 0.432   Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-_esqfh3v
#0 16.55   Resolved https://github.com/huggingface/transformers to commit d6f1da6b7169e3b2bcc2fcdc91a19171ecafeb88
#0 16.55   Installing build dependencies: started
#0 151.3   Installing build dependencies: still running...
#0 151.4   Installing build dependencies: finished with status 'error'
#0 151.4   error: subprocess-exited-with-error
#0 151.4   
#0 151.4   × pip subprocess to install build dependencies did not run successfully.
#0 151.4   │ exit code: 2
#0 151.4   ╰─> [81 lines of output]
#0 151.4       Collecting setuptools>=40.8.0
#0 151.4         Downloading setuptools-67.7.2-py3-none-any.whl (1.1 MB)
#0 151.4            ━━━━━━━━━━━━━                            0.4/1.1 MB 4.6 kB/s eta 0:02:39
#0 151.4       ERROR: Exception:
#0 151.4       Traceback (most recent call last):
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
#0 151.4           yield
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
#0 151.4           data = self._fp_read(amt) if not fp_closed else b""
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
#0 151.4           return self._fp.read(amt) if amt is not None else self._fp.read()
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
#0 151.4           data = self.__fp.read(amt)
#0 151.4         File "/usr/local/lib/python3.10/http/client.py", line 466, in read
#0 151.4           s = self.fp.read(amt)
#0 151.4         File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
#0 151.4           return self._sock.recv_into(b)
#0 151.4         File "/usr/local/lib/python3.10/ssl.py", line 1274, in recv_into
#0 151.4           return self.read(nbytes, buffer)
#0 151.4         File "/usr/local/lib/python3.10/ssl.py", line 1130, in read
#0 151.4           return self._sslobj.read(len, buffer)
#0 151.4       TimeoutError: The read operation timed out
#0 151.4       
#0 151.4       During handling of the above exception, another exception occurred:
#0 151.4       
#0 151.4       Traceback (most recent call last):
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
#0 151.4           status = run_func(*args)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
#0 151.4           return func(self, options, args)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
#0 151.4           requirement_set = resolver.resolve(
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
#0 151.4           result = self._result = resolver.resolve(
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
#0 151.4           state = resolution.resolve(requirements, max_rounds=max_rounds)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
#0 151.4           self._add_to_criteria(self.state.criteria, r, parent=None)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
#0 151.4           if not criterion.candidates:
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
#0 151.4           return bool(self._sequence)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#0 151.4           return any(self)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#0 151.4           return (c for c in iterator if id(c) not in self._incompatible_ids)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#0 151.4           candidate = func()
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
#0 151.4           self._link_candidate_cache[link] = LinkCandidate(
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
#0 151.4           super().__init__(
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
#0 151.4           self.dist = self._prepare()
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
#0 151.4           dist = self._prepare_distribution()
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
#0 151.4           return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
#0 151.4           return self._prepare_linked_requirement(req, parallel_builds)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 587, in _prepare_linked_requirement
#0 151.4           local_file = unpack_url(
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
#0 151.4           file = get_http_url(
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
#0 151.4           from_path, content_type = download(link, temp_dir.path)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
#0 151.4           for chunk in chunks:
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
#0 151.4           for chunk in iterable:
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
#0 151.4           for chunk in response.raw.stream(
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
#0 151.4           data = self.read(amt=amt, decode_content=decode_content)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
#0 151.4           with self._error_catcher():
#0 151.4         File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
#0 151.4           self.gen.throw(typ, value, traceback)
#0 151.4         File "/usr/local/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
#0 151.4           raise ReadTimeoutError(self._pool, None, "Read timed out.")
#0 151.4       pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
#0 151.4       [end of output]
#0 151.4   
#0 151.4   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 151.4 error: subprocess-exited-with-error
#0 151.4 
#0 151.4 × pip subprocess to install build dependencies did not run successfully.
#0 151.4 │ exit code: 2
#0 151.4 ╰─> See above for output.
#0 151.4 
#0 151.4 note: This error originates from a subprocess, and is likely not a problem with pip.
------
failed to solve: executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements-mac.txt]: exit code: 1

**Comment by Captain-Bacon** [comment] 2023-04-24 15:51
I've deleted the entire folder for Agent LLM, re-cloned the distro, got further this time, but now I'm stuck with the same Network Error when running. "docker-compose -f docker-compose-mac.yml up -d --build"


<img width="880" alt="Screenshot 2023-04-24 at 16 49 13" src="https://user-images.githubusercontent.com/123217107/234049871-82b1f3a6-ae7d-47f7-ad08-f5ff5d7f4aa1.png">

**Comment by Aopenz** [comment] 2023-04-24 16:22
same Network Error when running

**Comment by Captain-Bacon** [comment] 2023-04-24 19:12
@Josh-XT Just checking in - was wondering if there was any likelihood of an update today, as I'm on the edge of my seat!

**Comment by Josh-XT** [comment] 2023-04-24 20:36
> @Josh-XT Just checking in - was wondering if there was any likelihood of an update today, as I'm on the edge of my seat!

Sorry, day job requiring my attention. :)

I am wondering if trying to do a docker prune.  This will gut all of your docker stuff, so if you have other docker stuff running, it will break it, so maybe don't do it.

Use with caution.  It will purge all volumes and containers for docker and make your docker like a fresh install.

```
docker system prune -a --volumes
```

**Comment by Captain-Bacon** [comment] 2023-04-24 20:39
No worries, I’ll give it a whirl, thanks!

FWIW I tried it on parallels too with a windows install - same problem.

**Comment by bozo32** [comment] 2023-04-24 20:58
did
docker-compose down
docker-compose -f docker-compose-mac.yml down
docker system prune -a --volumes (12 gb of things I'd forgotten existed poof :) )
 docker-compose -f docker-compose-mac.yml up --build -d

install completed with no apparent errors
[+] Running 3/3
 ⠿ Network agent-llm_default       Created                                                                                   0.0s
 ⠿ Container agent-llm-backend-1   Started                                                                                   0.5s
 ⠿ Container agent-llm-frontend-1  Started                                                                                   0.7s

localhost:5000 is blank
localhost:5001 is {"detail":"Not Found"}
running m1 from a conda environment python 3.10 that I created using your requirements.txt...but that shouldn't make any difference should it?

-Peter

**Comment by alifanov** [comment] 2023-04-24 22:13
I suppose the problem with env
Added console.log for JS app - process.env.NEXT_PUBLIC_API_URI=undefined

**Comment by Aopenz** [comment] 2023-04-25 02:17
‘docker system prune -a --volumes’，The command has been executed, Also re-cloned the program，but there is still a network error

**Comment by Josh-XT** [comment] 2023-04-25 17:28
Can you guys see if anything is any better with the latest release?

**Comment by Captain-Bacon** [comment] 2023-04-25 17:35
> Can you guys see if anything is any better with the latest release?

@Josh-XT 0 131.0 Get:11 http://deb.debian.org/debian buster/main amd64 xz-utils amd64 5.2.4-1+deb10u1 [183 kB]
#0 131.1 Fetched 61.6 MB in 2min 9s (477 kB/s)
#0 131.1 W: http://deb.debian.org/debian/pool/main/g/gcc-defaults/cpp_8.3.0-1_amd64.deb: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
#0 131.1 E: Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/k/krb5/libgssapi-krb5-2_1.17-3+deb10u5_amd64.deb  400  Bad Request [IP: 151.101.62.132 80]
#0 131.1 E: Failed to fetch http://deb.debian.org/debian/pool/main/b/binutils/binutils-common_2.31.1-16_amd64.deb  Temporary failure resolving 'deb.debian.org' [IP: 151.101.62.132 80]
#0 131.1 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
failed to solve: executor failed running [/bin/sh -c apt-get install -y --no-install-recommends git build-essential]: exit code: 100

**Comment by alifanov** [comment] 2023-04-25 17:58
![image](https://user-images.githubusercontent.com/2394285/234362216-ad78bfe3-baa4-4880-a158-e14e9ebab04f.png)

**Comment by Captain-Bacon** [comment] 2023-04-25 18:17
<img width="1669" alt="Screenshot 2023-04-25 at 19 16 47" src="https://user-images.githubusercontent.com/123217107/234366244-e5ccd25b-0a95-4176-abfa-f1ca6158e646.png">

**Comment by bozo32** [comment] 2023-04-25 20:15
I'm getting the same as Mr Bacon
for context...clip from .env file

both are tested and known good.

# =========================
# AI PROVIDER: OPENAI
# =========================
OPENAI_API_KEY="sk-whatever"

snip
# =========================
# AI PROVIDER: LLAMACPP
# =========================
MODEL_PATH="/Users/peter/ai-computing-assistant/llama.cpp/models/7B/ggml-model-q4_0.bin"

**Comment by Josh-XT** [comment] 2023-04-26 02:36
I've updated the back end port to 7437.  Please update to v1.1.0 and let me know if you're still having issues.

https://github.com/Josh-XT/Agent-LLM/releases/tag/v1.1.0

**Comment by Aopenz** [comment] 2023-04-26 05:28
Error!
Network Error @Josh-XT

**Comment by bozo32** [comment] 2023-04-26 06:45
just did a full prune and re-install

2023-04-26 08:43:16 (15,2 MB/s) - ‘docker-compose-mac.yml’ saved [574/574]
(agent-llm-3.10) peter@peter agent-llm % docker compose -f docker-compose-mac.yml up -d
[+] Running 0/1
 ⠙ frontend Pulling                                                                                                                1.1s
no matching manifest for linux/arm64/v8 in the manifest list entries
(agent-llm-3.10) peter@peter agent-llm %

**Comment by bozo32** [comment] 2023-04-26 07:39
the updated version above didn't work either.server dropped apparently. is there a debug stream somewhere I could be capturing that would be useful?

**Comment by bigr00** [comment] 2023-04-28 06:59
After prune and reinstall and a modification to the dockerfiles to include arm64, it works! Nice job!

So for an M1 Macbook I had to do the following changes:
1. Change the frontend Dockerfile
![Screenshot 2023-04-28 at 09 54 47](https://user-images.githubusercontent.com/28863322/235076255-d8823bf4-8b58-4098-92ab-be436cf81155.png)
2. Change the backend Dockerfile-backend
![Screenshot 2023-04-28 at 09 55 24](https://user-images.githubusercontent.com/28863322/235076374-8ec4fd95-cb22-4b12-8dd9-06da21be0c12.png)
3. Change docker-compose-mac.yml
![Screenshot 2023-04-28 at 09 55 41](https://user-images.githubusercontent.com/28863322/235076524-dc5c6f18-dbe1-450a-a7d9-82374e1839b4.png)

Then a good old docker prune and 541 seconds later:
![Screenshot 2023-04-28 at 09 56 39](https://user-images.githubusercontent.com/28863322/235076693-b250a071-464e-41de-bc49-9fdb0c1258ef.png)


So now I got to a better state with the frontend itself, it now at least shows when the task starts, but does not update the frontend with anything going on in the backend afterwards. I would say this is a better state than before, but ultimately still not usable, as there are no updates coming to the frontend.

I looked into if it's possible to detect the architecture of the system in Docker setup and unfortunately the only good solution I was able to find is an environment variable setup that needs to be executed from a separate python file:
`#!/bin/sh

if [ "$(uname -sm)" == "Darwin arm64" ]; then
  export DOCKERFILE_BACKEND="Dockerfile-backend-m1"
else
  export DOCKERFILE_BACKEND="Dockerfile-backend"
fi

docker compose up -d
`

**Comment by Josh-XT** [comment] 2023-04-29 11:55
Can you try the latest?  We did a bunch of bug fixes over the past 24 hours.

**Comment by Josh-XT** [comment] 2023-04-29 12:03
Core of this main issue was resolved by changing our back end port.  Other issues with docker not communicating back end with front end, please move that conversation to #79

**Closed by Josh-XT** 2023-04-29 12:03 UTC
Labels: type | report | incompatibility, platform | macos

**Comment by Aopenz** [comment] 2023-04-29 12:47
Been following the updates, but unfortunately, have not used them successfully. Now the network error is solved, but the program doesn't do any work and the agent chat button is grayed out. It would be great if you could record a Youtube video with the detailed steps from installation to use. Thanks for your hard work! @Josh-XT

**Comment by bigr00** [comment] 2023-04-29 13:48
I completely agree with @Aopenz - we currently have no idea what are the expected features, working blind here. Would love to see how the frontend is supposed to behave.
