### ISSUE TITLE
Requests Made to Localhost Even With Remote / Containerized Deployment

### ISSUE THREAD

**Issue by Electrofried** [Josh-XT/Agent-LLM#114] opened 2023-04-26 15:38 UTC
### Title

Frontend has no respect for backend location

### Description

So when you load the frontend and backend on a remote location, like say via docker, the frontend does not take in to consideration the location of the backend and simply tries to connect over localhost. Well, obviously that causes some minor issues if your local host does not happen to be running the backend.

### Steps to Reproduce

Load the docker image (or even just an install in a VM/remote server I would assume)
Open the frontend
it does not work
see browser is making a lot of requests to localhost.

### Expected Behavior

Frontend should probably use the referrer, or have some configuration option in the off chance someone does something silly like hosting the back end and front end in totally separate network locations. It probably should never be just looking at localhost.

### Actual Behavior

Frontend ignores my wishes and wants to talk to my unresponsive localhost.

### Additional Context

![image](https://user-images.githubusercontent.com/27886155/234628142-6ef1d9bb-0494-4117-a484-bdfae42a8b95.png)

### Python Version

- [ ] Python <= 3.9
- [X] Python 3.10
- [ ] Python 3.11

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet
- [X] I am using the latest version of the software
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue

**Comment by Josh-XT** [comment] 2023-04-26 15:41
@JamesonRGrieve will need to take a look at this one.  Thank you.

**Comment by alexl83** [comment] 2023-04-26 16:19
I suppose it could be related to #79

**Comment by Electrofried** [comment] 2023-04-26 21:29
Oh, almost certainly. It seems most people there are accessing the front end remotely. 

Sorry, I did not spot the issue before I posted.

**Comment by 23andreas** [comment] 2023-04-29 15:58
This is not a duplicate of #79. In #79 it was using port 5000, from the screenshot posted here you can see it's using correct port  7437. 

I believe the issue here is env variables are not loaded correctly by the frontend application. 
https://github.com/Josh-XT/Agent-LLM/blob/a05d2dd948d5db091e28524803d5d9eee4f38233/frontend/pages/agent/index.js#L10 this line returns localhost, even though NEXT_PUBLIC_API_URI seems to be set correctly

``` 
/app # echo $NEXT_PUBLIC_API_URI
https://agent-llm-backend.gafro.net
```

**Comment by Josh-XT** [comment] 2023-04-29 16:34
> I don't think this is a duplicate of #79. In #79 it was using port 5000, from the screenshot posted here you can see it's using correct port 7437.
> 
> I believe the issue here is env variables are not loaded correctly by the frontend application.
> 
> https://github.com/Josh-XT/Agent-LLM/blob/a05d2dd948d5db091e28524803d5d9eee4f38233/frontend/pages/agent/index.js#L10
> 
> this line returns localhost, even though NEXT_PUBLIC_API_URI seems to be set correctly when I open a shell in the container
> ```
> /app # echo $NEXT_PUBLIC_API_URI
> https://agent-llm-backend.homeserver.local
> ```

I'm not sure what you're doing.  The docker-compose is set up to run the front end and back end on the same machine.  If you need to access them remotely (from another machine), you need to figure out whatever firewall/routing rules you need in order to make that work.  That isn't a scenario I'm prepared to support.  Our supported scenario is running the docker-compose on the machine you intend to use it on, both front and back end.

**Closed by Josh-XT** 2023-04-29 16:34 UTC
Labels: type | report | bug, area | front end, environment | docker / containerized, environment | remote

**Comment by 23andreas** [comment] 2023-04-29 16:50
> 



> > I don't think this is a duplicate of #79. In #79 it was using port 5000, from the screenshot posted here you can see it's using correct port 7437.
> > I believe the issue here is env variables are not loaded correctly by the frontend application.
> > https://github.com/Josh-XT/Agent-LLM/blob/a05d2dd948d5db091e28524803d5d9eee4f38233/frontend/pages/agent/index.js#L10
> > 
> > this line returns localhost, even though NEXT_PUBLIC_API_URI seems to be set correctly when I open a shell in the container
> > ```
> > /app # echo $NEXT_PUBLIC_API_URI
> > https://agent-llm-backend.homeserver.local
> > ```
> 
> I'm not sure what you're doing. The docker-compose is set up to run the front end and back end on the same machine. If you need to access them remotely (from another machine), you need to figure out whatever firewall/routing rules you need in order to make that work. That isn't a scenario I'm prepared to support. Our supported scenario is running the docker-compose on the machine you intend to use it on, both front and back end.

Thanks for taking a look at this, 
I have a server setup in my home network. I'm trying to run this on it.
I'm running both front and back end on my server. Both services are running fine and I can access them, however when I access the frontend it always tries to query localhost:7437. It looks like it should be possible to override which endpoint is used for the backend by using the `$NEXT_PUBLIC_API_URI` env variable, but it seems like it's not loading that correctly and defaulting to localhost:7437

**Comment by TheMasterFX** [comment] 2023-04-29 20:35
Same issue here.
I'm running front and backend on a different machine in my network "agent-llm.fritz.box"
My compose file looks like this
```yaml
version: "3.8"
services:
  frontend:
    build: ./frontend
    init: true
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URI: ${NEXT_PUBLIC_API_URI:-http://agent-llm.fritz.box:7437}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    init: true
    env_file:
      - .env
    ports:
      - "7437:7437"
    volumes:
      - ./data/agents:/app/agents:rw
      - ./data/workspace:/app/WORKSPACE:rw
      - ./models:/model:rw
```
On podman-compose up the it looks okay (NEXT_PUBLIC_API_URI is set):
```
['podman', 'network', 'exists', 'agent-llm_default']
podman create --name=agent-llm_frontend_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=agent-llm --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=agent-llm --label com.docker.compose.project.working_dir=/home/masterfx/Agent-LLM --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=frontend --env-file /home/masterfx/Agent-LLM/.env -e NEXT_PUBLIC_API_URI=http://agent-llm.box:7437 --net agent-llm_default --network-alias frontend -p 3000:3000 --init agent-llm_frontend
7f6a0f4754e5a1cea74151de62ae854c94d6bd9e4d8bd22015afbbae9a0b59f1
exit code: 0
```
When I open the frontent, all request still go to localhost...

**Comment by TheMasterFX** [comment] 2023-04-29 22:59
Sorry, my fault. I did't realize that the NEXT_PUBLIC_API_URI  is basically hardcoded to the frontend. So before building the frontend container the NEXT_PUBLIC_API_URI has to be set properly

**Comment by DIGist** [comment] 2023-04-30 02:37
> I don't think this is a duplicate of #79. In #79 it was using port 5000, from the screenshot posted here you can see it's using correct port 7437.
> 
> I believe the issue here is env variables are not loaded correctly by the frontend application.
> 
> https://github.com/Josh-XT/Agent-LLM/blob/a05d2dd948d5db091e28524803d5d9eee4f38233/frontend/pages/agent/index.js#L10
> 
> this line returns localhost, even though NEXT_PUBLIC_API_URI seems to be set correctly when I open a shell in the container
> ```
> /app # echo $NEXT_PUBLIC_API_URI
> https://agent-llm-backend.homeserver.local
> ```

Just for reference, at least in my case it is a duplicate issue, I think that issue was reported before the backend moved from port 5000 to port 7437.

**Comment by luisalrp** [comment] 2023-04-30 15:50
I have the same problem. I use the docker images published as packages and run it on a server. Both dockers in the same server with bridge network.

As @TheMasterFX points, frontend docker is not paying attention to the value of NEXT_PUBLIC_API_URI since it is just used in build time and not in run time, right?

**Comment by Daxiongmao87** [comment] 2023-05-07 05:34
I've also been running into this issue.  I've cleared my docker cache, made sure the variable is correct, and rebuilt, and still its showing localhost on the frontend console.

**Comment by TheMasterFX** [comment] 2023-05-07 14:12
Try to create a ".env.local" in the frontend directory with "NEXT_PUBLIC_API_URI=http://yourhostname.local:7437" and then create everything again

**Comment by Daxiongmao87** [comment] 2023-05-07 18:08
Thanks for the suggestion. I instead used my server's ip address since this is run on a separate, headless server, and I wish to access it on my desktop.  The error now instead is an SSL wrong version number error:
```
frontend_1  | (node:29) UnhandledPromiseRejectionWarning: Error: write EPROTO 139999215586120:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
frontend_1  |
frontend_1  |     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
frontend_1  |     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:591:25)
frontend_1  |     at RedirectableRequest.emit (events.js:400:28)
frontend_1  |     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
frontend_1  |     at ClientRequest.emit (events.js:400:28)
frontend_1  |     at TLSSocket.socketErrorListener (_http_client.js:475:9)
frontend_1  |     at TLSSocket.emit (events.js:400:28)
frontend_1  |     at emitErrorNT (internal/streams/destroy.js:106:8)
frontend_1  |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
frontend_1  |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
frontend_1  | (Use `node --trace-warnings ...` to show where the warning was created)
frontend_1  | (node:29) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
frontend_1  | (node:29) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

With the backend also returning:
```
backend_1   | WARNING:  Invalid HTTP request received.
```

So it seems they are communicating now, but I'm now having SSL issues.

**Comment by Daxiongmao87** [comment] 2023-05-07 19:34
Thank you, that seemed to have done the trick!

**Comment by dmt816** [comment] 2023-05-09 07:27
> Try to create a ".env.local" in the frontend directory with "NEXT_PUBLIC_API_URI=http://yourhostname.local:7437" and then create everything again

This worked for me until I recloned the repository and am now missing the frontend folder. Looks like it's not building the frontend image locally anymore so I'm unable to modify the env and the issue recurs.
